#home:
#  path: /
#  controller: App\Controller\DefaultController::index
#  methods: GET

controllers:
  resource: '../src/App/Controller/'
  type: annotation

setupcheck:
  path: /api/setup-check
  controller: App\Controller\DefaultController::setupCheck
  methods: [GET]

index:
  path: /{wildcard}
  controller: App\Controller\DefaultController::index
  requirements:
    wildcard: .*
  methods: [GET]


